version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7.2-alpine
    container_name: deepresearch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - deepresearch

  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: deepresearch-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - deepresearch

  # Frontend (optional - for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deepresearch-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - deepresearch

volumes:
  redis_data:
    driver: local

networks:
  deepresearch:
    driver: bridge

